### ISSUE TITLE
Starting Cypress error

### ISSUE THREAD

**Issue by Slobo989** [JasonLandbridge/Cypress-Auth0-Simulator#1]
Hello,
first of all, thank you for creating this package for Cypress 13.
 I have a problem when starting Cypress. Using Cypress version 13.5.1.
 
<img width="400" alt="Screenshot 2023-11-21 at 10 40 38" src="https://github.com/JasonLandbridge/Cypress-Auth0-Simulator/assets/39959907/5d3818c6-0661-437b-bd95-270c3739db0a">

Also, I am using `import { encrypt } from 'cypress-auth0-simulator';`
and i am getting TS error `Module '"cypress-auth0-simulator"' has no exported member 'encrypt'.ts(2305)`

Maybe i didn't configure something right?

**Comment by JasonLandbridge** [comment]
Hey, sorry but this package is not working. I had to abandon the idea due to many issues that I couldn't overcome in a short time. I will archive this repo and delete the NPM package.
